# Generated by Django 2.2.1 on 2019-06-02 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carmakename', models.CharField(blank=True, max_length=255, null=True)),
                ('cardescription', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewtitle', models.CharField(max_length=255)),
                ('reviewdate', models.DateField()),
                ('rating', models.SmallIntegerField()),
                ('reviewtext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carmodelname', models.CharField(max_length=255)),
                ('carprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manifacturingdate', models.DateField()),
                ('carmillage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cardescription', models.TextField(blank=True, null=True)),
                ('Carmake', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carapp.CarMake')),
            ],
        ),
    ]
